# Generated by Django 3.2.8 on 2023-08-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='titulo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Nombre',
            field=models.CharField(default=28, max_length=100, verbose_name='NombreJOHN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='DescripcionJOHN'),
        ),
    ]
