# Generated by Django 3.2.8 on 2023-08-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_cliente_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='titulo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Apellido',
            field=models.CharField(default=' ', max_length=100, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Correo',
            field=models.CharField(default=' ', max_length=100, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='HistorialConsultas',
            field=models.TextField(null=True, verbose_name='Descripcion Cotizacion'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Nombre',
            field=models.CharField(default=' ', max_length=100, verbose_name='Nombre'),
        ),
    ]
