# Generated by Django 3.2.8 on 2023-08-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_auto_20230818_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
